//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/29
//  @ Author : 211506342
//
//


#include "StaticData.h"
#using <mscorlib.dll>

StaticData* StaticData::sharedStaticData() {

}

StaticData::bool StaticData::init() {

}

void StaticData::stringFromKey(std::string Key) {

}

int StaticData::intFromKey(std::string Key) {

}

int StaticData::floatFromKey(std::string Key) {

}

bool StaticData::booleanFromKey(std::string Key) {

}

cocos2d::CCPoint StaticData::pointFromKey(std::string Key) {

}

cocos2d::CCRect StaticData::rectFromKey(std::string Key) {

}

cocos2d::CCSize StaticData::sizeFromKey(std::string Key) {

}

void StaticData::purge() {

}

StaticData::StaticData() {

}

StaticData::~StaticData() {

}

