//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Fish
//  @ File Name : StaticData.h
//  @ Date : 2017/10/27
//  @ Author : 211506342 уег╛
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H

#include<string>
#include "cocos2d.h"
using namespace std;
USING_NS_CC;

#define STATIC_DATA_FILENAME "static_data.plist"
#define STATIC_DATA_STRING(key) StaticData::sharedStaticData()->stringValueFromKey(key)
#define STATIC_DATA_INT(key) StaticData::sharedStaticData()->intValueFromKey(key)
#define STATIC_DATA_FlOAT(key) StaticData::sharedStaticData()->floatValueFromKey(key)
#define STATIC_DATA_BOOL(key) StaticData::sharedStaticData()->booleanFromKey(key)
#define STATIC_DATA_POINT(key) StaticData::sharedStaticData()->pointFromKey(key)
#define STATIC_DATA_RECT(key) StaticData::sharedStaticData()->rectFromKey(key)
#define STATIC_DATA_SIZE(key) StaticData::sharedStaticData()->sizeFromKey(key)


class StaticData:
	public CCObject {
public:
	static StaticData* sharedStaticData();
	static void purge();
	int intValueFromKey(string key);
	const char* stringValueFromKey(string key);
	float floatValueFromKey(string key);
	bool booleanFromKey(string key);
	CCPoint pointFromKey(string key);
	CCRect rectFromKey(string key);
	CCSize sizeFromKey(string key);
protected:
	CCDictionary* _dictionary;
	string _staticFileName;
	bool init();
private:
	~StaticData();
	StaticData();
};

#endif  //_STATICDATA_H
